/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestSearchRouteImport } from './routes/test-search'
import { Route as TestPasswordRouteImport } from './routes/test-password'
import { Route as TestPaginationRouteImport } from './routes/test-pagination'
import { Route as TestAccordionRouteImport } from './routes/test-accordion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TestSearchRoute = TestSearchRouteImport.update({
  id: '/test-search',
  path: '/test-search',
  getParentRoute: () => rootRouteImport,
} as any)
const TestPasswordRoute = TestPasswordRouteImport.update({
  id: '/test-password',
  path: '/test-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TestPaginationRoute = TestPaginationRouteImport.update({
  id: '/test-pagination',
  path: '/test-pagination',
  getParentRoute: () => rootRouteImport,
} as any)
const TestAccordionRoute = TestAccordionRouteImport.update({
  id: '/test-accordion',
  path: '/test-accordion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test-accordion': typeof TestAccordionRoute
  '/test-pagination': typeof TestPaginationRoute
  '/test-password': typeof TestPasswordRoute
  '/test-search': typeof TestSearchRoute
  '/api/$': typeof ApiSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test-accordion': typeof TestAccordionRoute
  '/test-pagination': typeof TestPaginationRoute
  '/test-password': typeof TestPasswordRoute
  '/test-search': typeof TestSearchRoute
  '/api/$': typeof ApiSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test-accordion': typeof TestAccordionRoute
  '/test-pagination': typeof TestPaginationRoute
  '/test-password': typeof TestPasswordRoute
  '/test-search': typeof TestSearchRoute
  '/api/$': typeof ApiSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test-accordion'
    | '/test-pagination'
    | '/test-password'
    | '/test-search'
    | '/api/$'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test-accordion'
    | '/test-pagination'
    | '/test-password'
    | '/test-search'
    | '/api/$'
    | '/api/auth/$'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/test-accordion'
    | '/test-pagination'
    | '/test-password'
    | '/test-search'
    | '/api/$'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestAccordionRoute: typeof TestAccordionRoute
  TestPaginationRoute: typeof TestPaginationRoute
  TestPasswordRoute: typeof TestPasswordRoute
  TestSearchRoute: typeof TestSearchRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-search': {
      id: '/test-search'
      path: '/test-search'
      fullPath: '/test-search'
      preLoaderRoute: typeof TestSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-password': {
      id: '/test-password'
      path: '/test-password'
      fullPath: '/test-password'
      preLoaderRoute: typeof TestPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-pagination': {
      id: '/test-pagination'
      path: '/test-pagination'
      fullPath: '/test-pagination'
      preLoaderRoute: typeof TestPaginationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-accordion': {
      id: '/test-accordion'
      path: '/test-accordion'
      fullPath: '/test-accordion'
      preLoaderRoute: typeof TestAccordionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestAccordionRoute: TestAccordionRoute,
  TestPaginationRoute: TestPaginationRoute,
  TestPasswordRoute: TestPasswordRoute,
  TestSearchRoute: TestSearchRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
